import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import type { PlanSettings, Profile, StudyRecord } from "./types";
import {
  createProfile as createProfileStorage,
  deleteProfile as deleteProfileStorage,
  getActiveProfileId,
  getGeneratedPlan,
  getPlanEdits,
  getPlanSettings,
  getProfiles,
  getRecords,
  saveGeneratedPlan,
  savePlanEdits,
  savePlanSettings,
  saveProfiles,
  saveRecords,
  setActiveProfileId,
  updateProfileName as updateProfileNameStorage,
} from "./storage";
import {
  adjustSettingsFromRecords,
  recordsSignature,
  buildAnalysisSuggestions,
  buildTomorrowSuggestion,
  generatePlan,
  suggestPlanAdjustment,
  getCauseCounts,
  getModuleTotals,
  getNextAction,
  getPlanHealth,
  getRecentStats,
  getTodayPlanDay,
  getUpcomingDays,
  normalizeSettings,
} from "./planner";
import { todayISO, getCorruptionCount } from "./utils";
import { toast } from "./toast";
import { schedulePush } from "./cloudSync";
import { getLocale, subscribeLocale, t } from "../i18n";
import { nextJlptExamDate } from "./constants";

import { StudyDeskContext, type StudyDeskContextValue, type StudyDeskState } from "./studyDeskContext";

function cleanupAutoGeneratedProfiles(profiles: Profile[]): Profile[] {
  const cleaned = profiles.filter((p) => !p.name.startsWith("设备 "));
  if (cleaned.length !== profiles.length) {
    saveProfiles(cleaned);
    Object.keys(localStorage).forEach((key) => {
      if (key.startsWith("jlptSprintDesk:fp_")) localStorage.removeItem(key);
    });
    localStorage.removeItem("jlptSprintDeskFingerprintProfile");
  }
  return cleaned;
}

function loadInitialState(): StudyDeskState {
  let profiles = cleanupAutoGeneratedProfiles(getProfiles());

  if (profiles.length === 0) {
    const defaultProfile: Profile = {
      id: "profile-default",
      name: getLocale() === "en" ? "Default profile" : "默认档案",
      createdAt: todayISO(),
      updatedAt: todayISO(),
    };
    profiles = [defaultProfile];
    saveProfiles(profiles);
    setActiveProfileId(defaultProfile.id);

    const defaultSettings = normalizeSettings({});
    savePlanSettings(defaultSettings, defaultProfile.id);

    saveRecords([], defaultProfile.id);

    return {
      profiles,
      activeProfileId: defaultProfile.id,
      settings: defaultSettings,
      generatedPlan: null,
      planEdits: {},
      records: [],
    };
  }

  const activeId = getActiveProfileId();
  const profileId = activeId && profiles.some((p) => p.id === activeId) ? activeId : profiles[0]?.id || null;

  if (profileId && profileId !== activeId) {
    setActiveProfileId(profileId);
  }

  const settings = profileId ? normalizeSettings(getPlanSettings(profileId)) : normalizeSettings({});
  const generatedPlan = profileId ? getGeneratedPlan(profileId) : null;
  const planEdits = profileId ? getPlanEdits(profileId) : {};
  const records = profileId ? getRecords(profileId) : [];

  return {
    profiles,
    activeProfileId: profileId,
    settings,
    generatedPlan,
    planEdits,
    records,
  };
}

export function StudyDeskProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<StudyDeskState>(loadInitialState);
  const lastSavedRef = useRef<StudyDeskState>(state);
  const [locale, setLocaleTick] = useState(getLocale());
  useEffect(() => subscribeLocale(() => setLocaleTick(getLocale())), []);

  useEffect(() => {
    if (getCorruptionCount() > 0) toast(t("toast.dataCorrupt"));
  }, []);

  const prevLocaleRef = useRef(locale);
  useEffect(() => {
    if (prevLocaleRef.current === locale) return;
    prevLocaleRef.current = locale;
    setState((prev) => {
      if (!prev.generatedPlan || !prev.activeProfileId) return prev;
      const plan = generatePlan(prev.settings, prev.activeProfileId);
      plan.adjustmentSignature = prev.generatedPlan.adjustmentSignature;
      saveGeneratedPlan(plan, prev.activeProfileId);
      const next = { ...prev, generatedPlan: plan };
      lastSavedRef.current = next;
      schedulePush();
      return next;
    });
  }, [locale]);

  const commit = useCallback((next: StudyDeskState): boolean => {
    setState(next);
    const prev = lastSavedRef.current;
    const samePid = prev.activeProfileId === next.activeProfileId;
    let ok = true;
    if (next.activeProfileId) {
      const pid = next.activeProfileId;
      if (!samePid || next.settings !== prev.settings) ok = savePlanSettings(next.settings, pid) && ok;
      if ((!samePid || next.generatedPlan !== prev.generatedPlan) && next.generatedPlan) ok = saveGeneratedPlan(next.generatedPlan, pid) && ok;
      if (!samePid || next.planEdits !== prev.planEdits) ok = savePlanEdits(next.planEdits, pid) && ok;
      if (!samePid || next.records !== prev.records) ok = saveRecords(next.records, pid) && ok;
    }
    if (next.profiles !== prev.profiles) ok = saveProfiles(next.profiles) && ok;
    lastSavedRef.current = next;
    schedulePush();
    if (!ok) toast(t("toast.saveFailed"));
    return ok;
  }, []);

  const todayRecord = useMemo(() => {
    return state.records.find((r) => r.date === todayISO()) || null;
  }, [state.records]);

  const todayPlan = useMemo(() => getTodayPlanDay(state.generatedPlan), [state.generatedPlan]);
  const upcomingDays = useMemo(() => getUpcomingDays(state.generatedPlan, 14), [state.generatedPlan]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const health = useMemo(() => getPlanHealth(state.generatedPlan, state.records), [state.generatedPlan, state.records, locale]);
  const stats = useMemo(() => getRecentStats(state.records, 7), [state.records]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const nextAction = useMemo(() => getNextAction(state.generatedPlan, todayRecord, health), [state.generatedPlan, todayRecord, health, locale]);
  const moduleTotals = useMemo(() => getModuleTotals(state.records), [state.records]);
  const causeCounts = useMemo(() => getCauseCounts(state.records), [state.records]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const suggestions = useMemo(() => buildAnalysisSuggestions(stats, health, moduleTotals, causeCounts, state.settings), [stats, health, moduleTotals, causeCounts, state.settings, locale]);
  const tomorrowSuggestion = useMemo(() => {
    if (!todayRecord) return null;
    return buildTomorrowSuggestion(todayRecord);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [todayRecord, locale]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const planAdjustment = useMemo(() => suggestPlanAdjustment(state.records, state.settings), [state.records, state.settings, locale]);

  const createProfile = useCallback((name: string) => {
    const profile = createProfileStorage(name);
    const next: StudyDeskState = {
      ...state,
      profiles: [...state.profiles, profile],
      activeProfileId: profile.id,
      settings: normalizeSettings({}),
      generatedPlan: null,
      planEdits: {},
      records: [],
    };
    setActiveProfileId(profile.id);
    if (commit(next)) toast(t("toast.profileCreated"));
  }, [state, commit]);

  const deleteProfile = useCallback((id: string) => {
    deleteProfileStorage(id);
    const nextProfiles = state.profiles.filter((p) => p.id !== id);
    const wasActive = state.activeProfileId === id;
    const next: StudyDeskState = wasActive
      ? (() => {
          const nextActiveId = nextProfiles[0]?.id || null;
          return {
            ...state,
            profiles: nextProfiles,
            activeProfileId: nextActiveId,
            settings: nextActiveId ? normalizeSettings(getPlanSettings(nextActiveId)) : normalizeSettings({}),
            generatedPlan: nextActiveId ? getGeneratedPlan(nextActiveId) : null,
            planEdits: nextActiveId ? getPlanEdits(nextActiveId) : {},
            records: nextActiveId ? getRecords(nextActiveId) : [],
          };
        })()
      : { ...state, profiles: nextProfiles };
    setState(next);
    lastSavedRef.current = next;
    schedulePush();
    toast(t("toast.profileDeleted"));
  }, [state]);

  const setActiveProfile = useCallback((id: string) => {
    setActiveProfileId(id);
    const next: StudyDeskState = {
      ...state,
      activeProfileId: id,
      settings: normalizeSettings(getPlanSettings(id)),
      generatedPlan: getGeneratedPlan(id),
      planEdits: getPlanEdits(id),
      records: getRecords(id),
    };
    toast(t("toast.profileSwitched"));
    setState(next);
    lastSavedRef.current = next;
    schedulePush();
  }, [state]);

  const updateProfileName = useCallback((id: string, name: string) => {
    updateProfileNameStorage(id, name);
    setState((prev) => ({
      ...prev,
      profiles: prev.profiles.map((p) => (p.id === id ? { ...p, name } : p)),
    }));
    schedulePush();
  }, []);

  const updateSettings = useCallback((patch: Partial<PlanSettings>) => {
    const nextSettings = normalizeSettings({ ...state.settings, ...patch });
    const next: StudyDeskState = { ...state, settings: nextSettings };
    commit(next);
  }, [state, commit]);

  const generateNewPlan = useCallback(() => {
    if (!state.activeProfileId) return;
    const plan = generatePlan(state.settings, state.activeProfileId);
    const next: StudyDeskState = { ...state, generatedPlan: plan, planEdits: {} };
    if (commit(next)) toast(t("toast.planGenerated"));
  }, [state, commit]);

  const advanceToNextExam = useCallback(() => {
    if (!state.activeProfileId) return;
    const nextSettings = normalizeSettings({ ...state.settings, examDate: nextJlptExamDate() });
    const plan = generatePlan(nextSettings, state.activeProfileId);
    if (commit({ ...state, settings: nextSettings, generatedPlan: plan, planEdits: {} })) {
      toast(t("toast.examAdvanced", { date: nextSettings.examDate }));
    }
  }, [state, commit]);

  const applyAutoAdjust = useCallback(() => {
    if (!state.generatedPlan || !state.activeProfileId) {
      toast(t("adjust.noPlan"));
      return;
    }
    const sig = recordsSignature(state.records);
    if (state.generatedPlan.adjustmentSignature === sig) {
      toast(t("adjust.alreadyApplied"));
      return;
    }
    const nextSettings = adjustSettingsFromRecords(state.settings, state.records);
    if (!nextSettings) {
      toast(t("adjust.alreadyApplied"));
      return;
    }
    const plan = generatePlan(nextSettings, state.activeProfileId);
    plan.adjustmentSignature = sig;
    if (commit({ ...state, settings: nextSettings, generatedPlan: plan })) toast(t("adjust.applied"));
  }, [state, commit]);

  const savePlanEdit = useCallback((dayIndex: number, text: string) => {
    const nextEdits = { ...state.planEdits };
    const value = text.trim();
    if (value) {
      nextEdits[String(dayIndex)] = value;
    } else {
      delete nextEdits[String(dayIndex)];
    }
    const next: StudyDeskState = { ...state, planEdits: nextEdits };
    if (commit(next)) toast(t("toast.dayEditSaved", { n: dayIndex }));
  }, [state, commit]);

  const deletePlanEdit = useCallback((dayIndex: number) => {
    const nextEdits = { ...state.planEdits };
    delete nextEdits[String(dayIndex)];
    const next: StudyDeskState = { ...state, planEdits: nextEdits };
    if (commit(next)) toast(t("toast.dayEditReset", { n: dayIndex }));
  }, [state, commit]);

  const saveRecord = useCallback((record: Partial<StudyRecord>) => {
    if (!state.activeProfileId) return;
    const now = todayISO();
    const existing = state.records.find((r) => r.id === record.id) || state.records.find((r) => r.date === now);

    const newRecord: StudyRecord = {
      id: existing?.id || `record-${Date.now()}`,
      date: existing?.date || record.date || now,
      profileId: state.activeProfileId,
      createdAt: existing?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      minutes: {},
      completion: "done",
      completionNote: "",
      accuracy: "",
      accuracyNote: "",
      wrongQuestionText: "",
      overtimeReason: "",
      timeNote: "",
      tomorrowFocus: "",
      causes: [],
      notes: "",
      ...existing,
      ...record,
    };

    const nextRecords = state.records.filter((r) => r.id !== newRecord.id);
    const sameDateIndex = nextRecords.findIndex((r) => r.date === newRecord.date);
    if (sameDateIndex >= 0) {
      nextRecords[sameDateIndex] = newRecord;
    } else {
      nextRecords.push(newRecord);
    }
    nextRecords.sort((a, b) => a.date.localeCompare(b.date));

    const next: StudyDeskState = { ...state, records: nextRecords };
    if (commit(next)) toast(newRecord.date === now ? t("record.savedToday") : t("record.savedOn", { date: newRecord.date }));
  }, [state, commit]);

  const deleteRecord = useCallback((id: string) => {
    const nextRecords = state.records.filter((r) => r.id !== id);
    const next: StudyDeskState = { ...state, records: nextRecords };
    if (commit(next)) toast(t("record.deleted"));
  }, [state, commit]);

  const value: StudyDeskContextValue = {
    state,
    todayRecord,
    todayPlan,
    upcomingDays,
    health,
    stats,
    nextAction,
    suggestions,
    tomorrowSuggestion,
    planAdjustment,
    moduleTotals,
    causeCounts,
    createProfile,
    deleteProfile,
    setActiveProfile,
    updateProfileName,
    updateSettings,
    generateNewPlan,
    advanceToNextExam,
    applyAutoAdjust,
    savePlanEdit,
    deletePlanEdit,
    saveRecord,
    deleteRecord,
  };

  return (
    <StudyDeskContext.Provider value={value}>
      {children}
    </StudyDeskContext.Provider>
  );
}
