import { useCallback, useMemo, useState, type ReactNode } from "react";
import type { GeneratedPlan, PlanEdits, PlanSettings, Profile, StudyRecord } from "./types";
import {
  createProfile as createProfileStorage,
  deleteProfile as deleteProfileStorage,
  getActiveProfileId,
  getGeneratedPlan,
  getPlanEdits,
  getPlanSettings,
  getProfiles,
  getRecords,
  saveGeneratedPlan,
  savePlanEdits,
  savePlanSettings,
  saveProfiles,
  saveRecords,
  setActiveProfileId,
  updateProfileName as updateProfileNameStorage,
} from "./storage";
import {
  buildAnalysisSuggestions,
  buildTomorrowSuggestion,
  generatePlan,
  getCauseCounts,
  getModuleTotals,
  getNextAction,
  getPlanHealth,
  getRecentStats,
  getTodayPlanDay,
  getUpcomingDays,
  normalizeSettings,
} from "./planner";
import { todayISO } from "./utils";
import { toast } from "./toast";

import { StudyDeskContext, type StudyDeskContextValue } from "./studyDeskContext";

interface StudyDeskState {
  profiles: Profile[];
  activeProfileId: string | null;
  settings: PlanSettings;
  generatedPlan: GeneratedPlan | null;
  planEdits: PlanEdits;
  records: StudyRecord[];
}

function cleanupAutoGeneratedProfiles(profiles: Profile[]): Profile[] {
  const cleaned = profiles.filter((p) => !p.name.startsWith("设备 "));
  if (cleaned.length !== profiles.length) {
    saveProfiles(cleaned);
    Object.keys(localStorage).forEach((key) => {
      if (key.startsWith("jlptSprintDesk:fp_")) localStorage.removeItem(key);
    });
    localStorage.removeItem("jlptSprintDeskFingerprintProfile");
  }
  return cleaned;
}

function loadInitialState(): StudyDeskState {
  let profiles = cleanupAutoGeneratedProfiles(getProfiles());

  if (profiles.length === 0) {
    const defaultProfile: Profile = {
      id: "profile-default",
      name: "默认档案",
      createdAt: todayISO(),
      updatedAt: todayISO(),
    };
    profiles = [defaultProfile];
    saveProfiles(profiles);
    setActiveProfileId(defaultProfile.id);

    const defaultSettings = normalizeSettings({});
    savePlanSettings(defaultSettings, defaultProfile.id);

    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const yesterdayStr = yesterday.toISOString().split("T")[0];

    const sampleRecords: StudyRecord[] = [
      {
        id: `record-${yesterdayStr}`,
        date: yesterdayStr,
        profileId: defaultProfile.id,
        createdAt: yesterdayStr,
        updatedAt: yesterdayStr,
        minutes: { kanji: 20, vocab: 30, grammar: 25, reading: 15, listening: 20 },
        moduleCounts: { kanji: 15, vocab: 50, grammar: 8, reading: 2, listening: 10 },
        completion: "done",
        completionNote: "",
        accuracy: "词汇 18/30，文法 12/20，听力 15/30",
        accuracyNote: "",
        wrongQuestionText: "",
        overtimeReason: "",
        timeNote: "听力部分耗时较长",
        tomorrowFocus: "加强听力练习",
        causes: [],
        notes: "今天状态不错，完成了所有计划任务。",
      },
      {
        id: `record-${todayISO()}`,
        date: todayISO(),
        profileId: defaultProfile.id,
        createdAt: todayISO(),
        updatedAt: todayISO(),
        minutes: { kanji: 15, vocab: 25, grammar: 20, reading: 10, listening: 15 },
        moduleCounts: { kanji: 10, vocab: 40, grammar: 6, reading: 1, listening: 8 },
        completion: "partial",
        completionNote: "阅读部分未完成",
        accuracy: "语言知识 30/45，阅读 18/30，听力 20/35",
        accuracyNote: "",
        wrongQuestionText: "",
        overtimeReason: "内容难度超预期",
        timeNote: "",
        tomorrowFocus: "补做阅读练习",
        causes: ["procrastination", "confused"],
        notes: "今天有些拖延，需要调整状态。",
      },
    ];
    saveRecords(sampleRecords, defaultProfile.id);

    return {
      profiles,
      activeProfileId: defaultProfile.id,
      settings: defaultSettings,
      generatedPlan: null,
      planEdits: {},
      records: sampleRecords,
    };
  }

  const activeId = getActiveProfileId();
  const profileId = activeId && profiles.some((p) => p.id === activeId) ? activeId : profiles[0]?.id || null;

  if (profileId && profileId !== activeId) {
    setActiveProfileId(profileId);
  }

  const settings = profileId ? normalizeSettings(getPlanSettings(profileId)) : normalizeSettings({});
  const generatedPlan = profileId ? getGeneratedPlan(profileId) : null;
  const planEdits = profileId ? getPlanEdits(profileId) : {};
  const records = profileId ? getRecords(profileId) : [];

  return {
    profiles,
    activeProfileId: profileId,
    settings,
    generatedPlan,
    planEdits,
    records,
  };
}

export function StudyDeskProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<StudyDeskState>(loadInitialState);

  const commit = useCallback((next: StudyDeskState) => {
    setState(next);
    if (next.activeProfileId) {
      savePlanSettings(next.settings, next.activeProfileId);
      if (next.generatedPlan) saveGeneratedPlan(next.generatedPlan, next.activeProfileId);
      savePlanEdits(next.planEdits, next.activeProfileId);
      saveRecords(next.records, next.activeProfileId);
    }
    saveProfiles(next.profiles);
  }, []);

  const todayRecord = useMemo(() => {
    return state.records.find((r) => r.date === todayISO()) || null;
  }, [state.records]);

  const todayPlan = useMemo(() => getTodayPlanDay(state.generatedPlan), [state.generatedPlan]);
  const upcomingDays = useMemo(() => getUpcomingDays(state.generatedPlan, 14), [state.generatedPlan]);
  const health = useMemo(() => getPlanHealth(state.generatedPlan, state.records), [state.generatedPlan, state.records]);
  const stats = useMemo(() => getRecentStats(state.records, 7), [state.records]);
  const nextAction = useMemo(() => getNextAction(state.generatedPlan, todayRecord, health), [state.generatedPlan, todayRecord, health]);
  const moduleTotals = useMemo(() => getModuleTotals(state.records), [state.records]);
  const causeCounts = useMemo(() => getCauseCounts(state.records), [state.records]);
  const suggestions = useMemo(() => buildAnalysisSuggestions(stats, health, moduleTotals, causeCounts, state.settings), [stats, health, moduleTotals, causeCounts, state.settings]);
  const tomorrowSuggestion = useMemo(() => {
    if (!todayRecord) return null;
    return buildTomorrowSuggestion(todayRecord);
  }, [todayRecord]);

  const createProfile = useCallback((name: string) => {
    const profile = createProfileStorage(name);
    const next: StudyDeskState = {
      ...state,
      profiles: [...state.profiles, profile],
      activeProfileId: profile.id,
      settings: normalizeSettings({}),
      generatedPlan: null,
      planEdits: {},
      records: [],
    };
    setActiveProfileId(profile.id);
    commit(next);
    toast("新学习档案已创建。");
  }, [state, commit]);

  const deleteProfile = useCallback((id: string) => {
    deleteProfileStorage(id);
    const nextProfiles = state.profiles.filter((p) => p.id !== id);
    const nextActiveId = nextProfiles[0]?.id || null;
    const next: StudyDeskState = {
      ...state,
      profiles: nextProfiles,
      activeProfileId: nextActiveId,
      settings: nextActiveId ? normalizeSettings(getPlanSettings(nextActiveId)) : normalizeSettings({}),
      generatedPlan: nextActiveId ? getGeneratedPlan(nextActiveId) : null,
      planEdits: nextActiveId ? getPlanEdits(nextActiveId) : {},
      records: nextActiveId ? getRecords(nextActiveId) : [],
    };
    setState(next);
    toast("学习档案已删除。");
  }, [state]);

  const setActiveProfile = useCallback((id: string) => {
    setActiveProfileId(id);
    const next: StudyDeskState = {
      ...state,
      activeProfileId: id,
      settings: normalizeSettings(getPlanSettings(id)),
      generatedPlan: getGeneratedPlan(id),
      planEdits: getPlanEdits(id),
      records: getRecords(id),
    };
    toast("已切换学习档案。");
    setState(next);
  }, [state]);

  const updateProfileName = useCallback((id: string, name: string) => {
    updateProfileNameStorage(id, name);
    setState((prev) => ({
      ...prev,
      profiles: prev.profiles.map((p) => (p.id === id ? { ...p, name } : p)),
    }));
  }, []);

  const updateSettings = useCallback((patch: Partial<PlanSettings>) => {
    const nextSettings = normalizeSettings({ ...state.settings, ...patch });
    const next: StudyDeskState = { ...state, settings: nextSettings };
    commit(next);
  }, [state, commit]);

  const generateNewPlan = useCallback(() => {
    if (!state.activeProfileId) return;
    const plan = generatePlan(state.settings, state.activeProfileId);
    const next: StudyDeskState = { ...state, generatedPlan: plan, planEdits: {} };
    commit(next);
    toast("新学习计划已生成。");
  }, [state, commit]);

  const savePlanEdit = useCallback((dayIndex: number, text: string) => {
    const nextEdits = { ...state.planEdits };
    const value = text.trim();
    if (value) {
      nextEdits[String(dayIndex)] = value;
    } else {
      delete nextEdits[String(dayIndex)];
    }
    const next: StudyDeskState = { ...state, planEdits: nextEdits };
    commit(next);
    toast(`Day ${dayIndex} 的调整已保存。`);
  }, [state, commit]);

  const deletePlanEdit = useCallback((dayIndex: number) => {
    const nextEdits = { ...state.planEdits };
    delete nextEdits[String(dayIndex)];
    const next: StudyDeskState = { ...state, planEdits: nextEdits };
    commit(next);
    toast(`Day ${dayIndex} 已恢复为生成计划。`);
  }, [state, commit]);

  const saveRecord = useCallback((record: Partial<StudyRecord>) => {
    if (!state.activeProfileId) return;
    const now = todayISO();
    const existing = state.records.find((r) => r.id === record.id) || state.records.find((r) => r.date === now);

    const newRecord: StudyRecord = {
      id: existing?.id || `record-${Date.now()}`,
      date: now,
      profileId: state.activeProfileId,
      createdAt: existing?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      minutes: {},
      completion: "done",
      completionNote: "",
      accuracy: "",
      accuracyNote: "",
      wrongQuestionText: "",
      overtimeReason: "",
      timeNote: "",
      tomorrowFocus: "",
      causes: [],
      notes: "",
      ...existing,
      ...record,
    };

    const nextRecords = state.records.filter((r) => r.id !== newRecord.id);
    const sameDateIndex = nextRecords.findIndex((r) => r.date === newRecord.date);
    if (sameDateIndex >= 0) {
      nextRecords[sameDateIndex] = newRecord;
    } else {
      nextRecords.push(newRecord);
    }
    nextRecords.sort((a, b) => a.date.localeCompare(b.date));

    const next: StudyDeskState = { ...state, records: nextRecords };
    commit(next);
    toast("今日学习记录已保存。");
  }, [state, commit]);

  const deleteRecord = useCallback((id: string) => {
    const nextRecords = state.records.filter((r) => r.id !== id);
    const next: StudyDeskState = { ...state, records: nextRecords };
    commit(next);
    toast("学习记录已删除。");
  }, [state, commit]);

  const value: StudyDeskContextValue = {
    state,
    todayRecord,
    todayPlan,
    upcomingDays,
    health,
    stats,
    nextAction,
    suggestions,
    tomorrowSuggestion,
    moduleTotals,
    causeCounts,
    createProfile,
    deleteProfile,
    setActiveProfile,
    updateProfileName,
    updateSettings,
    generateNewPlan,
    savePlanEdit,
    deletePlanEdit,
    saveRecord,
    deleteRecord,
  };

  return (
    <StudyDeskContext.Provider value={value}>
      {children}
    </StudyDeskContext.Provider>
  );
}

