import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import type { GeneratedPlan, PlanEdits, PlanSettings, Profile, StudyRecord } from "./types";
import {
  createProfile as createProfileStorage,
  deleteProfile as deleteProfileStorage,
  getActiveProfileId,
  getGeneratedPlan,
  getPlanEdits,
  getPlanSettings,
  getProfiles,
  getRecords,
  saveGeneratedPlan,
  savePlanEdits,
  savePlanSettings,
  saveProfiles,
  saveRecords,
  setActiveProfileId,
  updateProfileName as updateProfileNameStorage,
} from "./storage";
import {
  adjustSettingsFromRecords,
  recordsSignature,
  buildAnalysisSuggestions,
  buildTomorrowSuggestion,
  generatePlan,
  suggestPlanAdjustment,
  getCauseCounts,
  getModuleTotals,
  getNextAction,
  getPlanHealth,
  getRecentStats,
  getTodayPlanDay,
  getUpcomingDays,
  normalizeSettings,
} from "./planner";
import { todayISO, getCorruptionCount } from "./utils";
import { toast } from "./toast";
import { schedulePush } from "./cloudSync";
import { getLocale, subscribeLocale, t } from "../i18n";

import { StudyDeskContext, type StudyDeskContextValue } from "./studyDeskContext";

interface StudyDeskState {
  profiles: Profile[];
  activeProfileId: string | null;
  settings: PlanSettings;
  generatedPlan: GeneratedPlan | null;
  planEdits: PlanEdits;
  records: StudyRecord[];
}

function cleanupAutoGeneratedProfiles(profiles: Profile[]): Profile[] {
  const cleaned = profiles.filter((p) => !p.name.startsWith("设备 "));
  if (cleaned.length !== profiles.length) {
    saveProfiles(cleaned);
    Object.keys(localStorage).forEach((key) => {
      if (key.startsWith("jlptSprintDesk:fp_")) localStorage.removeItem(key);
    });
    localStorage.removeItem("jlptSprintDeskFingerprintProfile");
  }
  return cleaned;
}

function loadInitialState(): StudyDeskState {
  let profiles = cleanupAutoGeneratedProfiles(getProfiles());

  if (profiles.length === 0) {
    const defaultProfile: Profile = {
      id: "profile-default",
      name: getLocale() === "en" ? "Default profile" : "默认档案",
      createdAt: todayISO(),
      updatedAt: todayISO(),
    };
    profiles = [defaultProfile];
    saveProfiles(profiles);
    setActiveProfileId(defaultProfile.id);

    const defaultSettings = normalizeSettings({});
    savePlanSettings(defaultSettings, defaultProfile.id);

    // New users start with a clean slate — no fabricated records.
    // They'll see proper empty-state guidance on Dashboard / Record pages.
    saveRecords([], defaultProfile.id);

    return {
      profiles,
      activeProfileId: defaultProfile.id,
      settings: defaultSettings,
      generatedPlan: null,
      planEdits: {},
      records: [],
    };
  }

  const activeId = getActiveProfileId();
  const profileId = activeId && profiles.some((p) => p.id === activeId) ? activeId : profiles[0]?.id || null;

  if (profileId && profileId !== activeId) {
    setActiveProfileId(profileId);
  }

  const settings = profileId ? normalizeSettings(getPlanSettings(profileId)) : normalizeSettings({});
  const generatedPlan = profileId ? getGeneratedPlan(profileId) : null;
  const planEdits = profileId ? getPlanEdits(profileId) : {};
  const records = profileId ? getRecords(profileId) : [];

  return {
    profiles,
    activeProfileId: profileId,
    settings,
    generatedPlan,
    planEdits,
    records,
  };
}

export function StudyDeskProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<StudyDeskState>(loadInitialState);
  // Mirror of what's currently persisted, used by commit() to (a) write only the
  // slices that actually changed and (b) detect write failures (quota exceeded /
  // private mode) so we never falsely report a save as successful.
  const lastSavedRef = useRef<StudyDeskState>(state);
  // Recompute locale-dependent derived values (plan health, next action,
  // suggestions — all built from planner phrase tables) when language switches.
  const [locale, setLocaleTick] = useState(getLocale());
  useEffect(() => subscribeLocale(() => setLocaleTick(getLocale())), []);

  // loadInitialState() (in the useState initializer above) already read every
  // slice; if any failed to parse, the raw value was backed up to a __corrupt
  // key. Warn the user once so they know the blank state isn't a real data loss.
  useEffect(() => {
    if (getCorruptionCount() > 0) toast(t("toast.dataCorrupt"));
  }, []);

  // The plan is generated once and stored, with task prose baked in the active
  // language. When the user switches language, regenerate so the stored plan's
  // task titles/strategy/roadmap follow the new language too. Manual day-edits
  // (planEdits) are preserved.
  const prevLocaleRef = useRef(locale);
  useEffect(() => {
    if (prevLocaleRef.current === locale) return;
    prevLocaleRef.current = locale;
    setState((prev) => {
      if (!prev.generatedPlan || !prev.activeProfileId) return prev;
      const plan = generatePlan(prev.settings, prev.activeProfileId);
      plan.adjustmentSignature = prev.generatedPlan.adjustmentSignature;
      saveGeneratedPlan(plan, prev.activeProfileId);
      const next = { ...prev, generatedPlan: plan };
      lastSavedRef.current = next; // the regenerated plan is now persisted
      // The stored plan's prose just changed → mark local + mirror to cloud.
      schedulePush();
      return next;
    });
  }, [locale]);

  const commit = useCallback((next: StudyDeskState): boolean => {
    setState(next);
    const prev = lastSavedRef.current;
    const samePid = prev.activeProfileId === next.activeProfileId;
    let ok = true;
    if (next.activeProfileId) {
      const pid = next.activeProfileId;
      // Only re-serialize a slice when it actually changed (a record edit must not
      // rewrite the whole — potentially 100KB+ — generated plan). When the active
      // profile changed, every slice belongs to a new profile and must be written.
      if (!samePid || next.settings !== prev.settings) ok = savePlanSettings(next.settings, pid) && ok;
      if ((!samePid || next.generatedPlan !== prev.generatedPlan) && next.generatedPlan) ok = saveGeneratedPlan(next.generatedPlan, pid) && ok;
      if (!samePid || next.planEdits !== prev.planEdits) ok = savePlanEdits(next.planEdits, pid) && ok;
      if (!samePid || next.records !== prev.records) ok = saveRecords(next.records, pid) && ok;
    }
    if (next.profiles !== prev.profiles) ok = saveProfiles(next.profiles) && ok;
    lastSavedRef.current = next;
    // Mirror every local write up to the cloud (no-op when sync is disabled).
    schedulePush();
    if (!ok) toast(t("toast.saveFailed"));
    return ok;
  }, []);

  const todayRecord = useMemo(() => {
    return state.records.find((r) => r.date === todayISO()) || null;
  }, [state.records]);

  const todayPlan = useMemo(() => getTodayPlanDay(state.generatedPlan), [state.generatedPlan]);
  const upcomingDays = useMemo(() => getUpcomingDays(state.generatedPlan, 14), [state.generatedPlan]);
  // `locale` is intentionally in deps: these values are built from planner phrase
  // tables (via module-level t()), so they must recompute when language switches.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const health = useMemo(() => getPlanHealth(state.generatedPlan, state.records), [state.generatedPlan, state.records, locale]);
  const stats = useMemo(() => getRecentStats(state.records, 7), [state.records]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const nextAction = useMemo(() => getNextAction(state.generatedPlan, todayRecord, health), [state.generatedPlan, todayRecord, health, locale]);
  const moduleTotals = useMemo(() => getModuleTotals(state.records), [state.records]);
  const causeCounts = useMemo(() => getCauseCounts(state.records), [state.records]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const suggestions = useMemo(() => buildAnalysisSuggestions(stats, health, moduleTotals, causeCounts, state.settings), [stats, health, moduleTotals, causeCounts, state.settings, locale]);
  const tomorrowSuggestion = useMemo(() => {
    if (!todayRecord) return null;
    return buildTomorrowSuggestion(todayRecord);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [todayRecord, locale]);
  // Data-driven plan-adjustment advice (increase/decrease/maintain) from the
  // last 7 days; locale-reactive because the strings come from the dict.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const planAdjustment = useMemo(() => suggestPlanAdjustment(state.records, state.settings), [state.records, state.settings, locale]);

  const createProfile = useCallback((name: string) => {
    const profile = createProfileStorage(name);
    const next: StudyDeskState = {
      ...state,
      profiles: [...state.profiles, profile],
      activeProfileId: profile.id,
      settings: normalizeSettings({}),
      generatedPlan: null,
      planEdits: {},
      records: [],
    };
    setActiveProfileId(profile.id);
    if (commit(next)) toast(t("toast.profileCreated"));
  }, [state, commit]);

  const deleteProfile = useCallback((id: string) => {
    deleteProfileStorage(id);
    const nextProfiles = state.profiles.filter((p) => p.id !== id);
    // Only re-point the active profile when we deleted the one that was active.
    // (deleteProfileStorage already keeps localStorage's active id in sync the
    //  same way — deleting a NON-active profile must not switch the UI/storage.)
    const wasActive = state.activeProfileId === id;
    const next: StudyDeskState = wasActive
      ? (() => {
          const nextActiveId = nextProfiles[0]?.id || null;
          return {
            ...state,
            profiles: nextProfiles,
            activeProfileId: nextActiveId,
            settings: nextActiveId ? normalizeSettings(getPlanSettings(nextActiveId)) : normalizeSettings({}),
            generatedPlan: nextActiveId ? getGeneratedPlan(nextActiveId) : null,
            planEdits: nextActiveId ? getPlanEdits(nextActiveId) : {},
            records: nextActiveId ? getRecords(nextActiveId) : [],
          };
        })()
      : { ...state, profiles: nextProfiles };
    setState(next);
    lastSavedRef.current = next; // slices loaded from storage are already persisted
    schedulePush(); // profile data changed → mirror to cloud
    toast(t("toast.profileDeleted"));
  }, [state]);

  const setActiveProfile = useCallback((id: string) => {
    setActiveProfileId(id);
    const next: StudyDeskState = {
      ...state,
      activeProfileId: id,
      settings: normalizeSettings(getPlanSettings(id)),
      generatedPlan: getGeneratedPlan(id),
      planEdits: getPlanEdits(id),
      records: getRecords(id),
    };
    toast(t("toast.profileSwitched"));
    setState(next);
    lastSavedRef.current = next; // slices loaded from storage are already persisted
    schedulePush(); // active profile pointer changed → mirror to cloud
  }, [state]);

  const updateProfileName = useCallback((id: string, name: string) => {
    updateProfileNameStorage(id, name);
    setState((prev) => ({
      ...prev,
      profiles: prev.profiles.map((p) => (p.id === id ? { ...p, name } : p)),
    }));
    schedulePush(); // profile name changed → mirror to cloud
  }, []);

  const updateSettings = useCallback((patch: Partial<PlanSettings>) => {
    const nextSettings = normalizeSettings({ ...state.settings, ...patch });
    const next: StudyDeskState = { ...state, settings: nextSettings };
    commit(next);
  }, [state, commit]);

  const generateNewPlan = useCallback(() => {
    if (!state.activeProfileId) return;
    const plan = generatePlan(state.settings, state.activeProfileId);
    const next: StudyDeskState = { ...state, generatedPlan: plan, planEdits: {} };
    if (commit(next)) toast(t("toast.planGenerated"));
  }, [state, commit]);

  // Apply the data-driven adjustment by changing the time settings and
  // regenerating the plan, so the budget/pie/daily-target/tasks all stay
  // consistent. A records signature blocks re-applying for unchanged data.
  const applyAutoAdjust = useCallback(() => {
    if (!state.generatedPlan || !state.activeProfileId) {
      toast(t("adjust.noPlan"));
      return;
    }
    const sig = recordsSignature(state.records);
    if (state.generatedPlan.adjustmentSignature === sig) {
      toast(t("adjust.alreadyApplied"));
      return;
    }
    const nextSettings = adjustSettingsFromRecords(state.settings, state.records);
    if (!nextSettings) {
      toast(t("adjust.alreadyApplied"));
      return;
    }
    const plan = generatePlan(nextSettings, state.activeProfileId);
    plan.adjustmentSignature = sig;
    if (commit({ ...state, settings: nextSettings, generatedPlan: plan })) toast(t("adjust.applied"));
  }, [state, commit]);

  const savePlanEdit = useCallback((dayIndex: number, text: string) => {
    const nextEdits = { ...state.planEdits };
    const value = text.trim();
    if (value) {
      nextEdits[String(dayIndex)] = value;
    } else {
      delete nextEdits[String(dayIndex)];
    }
    const next: StudyDeskState = { ...state, planEdits: nextEdits };
    if (commit(next)) toast(t("toast.dayEditSaved", { n: dayIndex }));
  }, [state, commit]);

  const deletePlanEdit = useCallback((dayIndex: number) => {
    const nextEdits = { ...state.planEdits };
    delete nextEdits[String(dayIndex)];
    const next: StudyDeskState = { ...state, planEdits: nextEdits };
    if (commit(next)) toast(t("toast.dayEditReset", { n: dayIndex }));
  }, [state, commit]);

  const saveRecord = useCallback((record: Partial<StudyRecord>) => {
    if (!state.activeProfileId) return;
    const now = todayISO();
    const existing = state.records.find((r) => r.id === record.id) || state.records.find((r) => r.date === now);

    const newRecord: StudyRecord = {
      id: existing?.id || `record-${Date.now()}`,
      date: existing?.date || record.date || now,
      profileId: state.activeProfileId,
      createdAt: existing?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      minutes: {},
      completion: "done",
      completionNote: "",
      accuracy: "",
      accuracyNote: "",
      wrongQuestionText: "",
      overtimeReason: "",
      timeNote: "",
      tomorrowFocus: "",
      causes: [],
      notes: "",
      ...existing,
      ...record,
    };

    const nextRecords = state.records.filter((r) => r.id !== newRecord.id);
    const sameDateIndex = nextRecords.findIndex((r) => r.date === newRecord.date);
    if (sameDateIndex >= 0) {
      nextRecords[sameDateIndex] = newRecord;
    } else {
      nextRecords.push(newRecord);
    }
    nextRecords.sort((a, b) => a.date.localeCompare(b.date));

    const next: StudyDeskState = { ...state, records: nextRecords };
    if (commit(next)) toast(newRecord.date === now ? t("record.savedToday") : t("record.savedOn", { date: newRecord.date }));
  }, [state, commit]);

  const deleteRecord = useCallback((id: string) => {
    const nextRecords = state.records.filter((r) => r.id !== id);
    const next: StudyDeskState = { ...state, records: nextRecords };
    if (commit(next)) toast(t("record.deleted"));
  }, [state, commit]);

  const value: StudyDeskContextValue = {
    state,
    todayRecord,
    todayPlan,
    upcomingDays,
    health,
    stats,
    nextAction,
    suggestions,
    tomorrowSuggestion,
    planAdjustment,
    moduleTotals,
    causeCounts,
    createProfile,
    deleteProfile,
    setActiveProfile,
    updateProfileName,
    updateSettings,
    generateNewPlan,
    applyAutoAdjust,
    savePlanEdit,
    deletePlanEdit,
    saveRecord,
    deleteRecord,
  };

  return (
    <StudyDeskContext.Provider value={value}>
      {children}
    </StudyDeskContext.Provider>
  );
}
